{
 "title": "Global - Source",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rocm_num_gpus)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_utilization_percentage) / count(rocm_utilization_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rocm_vram_used_percentage) / count(rocm_vram_used_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rmsjob_info{jobid=~\"^[^\\\\s]+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Allocated GPUs",
   "type": "stat",
   "description": "Number of GPUs in nodes allocated to active jobs.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage * on (instance) group_left() (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average 1m Load Average.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(omnistat_host_cpu_load1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(omnistat_host_mem_available_bytes) / sum(omnistat_host_mem_total_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count by (jobid) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Number of Allocated GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(rocm_utilization_percentage * on (instance) group_left() (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network: Ethernet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(omnistat_network_rx_bytes{device_class=\"net\"}[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(omnistat_network_tx_bytes{device_class=\"net\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Network: High Performance Interconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval]))",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Types",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Driver",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU VBIOS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 682 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Type to VBIOS Mapping",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 682 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Detailed GPU Versions",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 688 },
     "targets": [
      { "expr": "rocm_version_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Index",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "timestamp(group by (jobid,user,batchflag,partition,nodes) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Occupancy (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Occupancy (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_utilization_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Top 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (Bottom 10 Jobs)",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))) / count by (jobid,user) (rocm_vram_used_percentage * on (instance) group_left(jobid,user) (count by (instance,jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Characterization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Core vs Memory per Job - Batch (1 min or longer)",
     "type": "xychart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "rocm_vram_used_percentage * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(group by (jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\", batchflag=\"1\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs - Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Duration Histogram - Batch",
     "type": "histogram",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(group by (jobid) (rmsjob_info{jobid=~\"^[^\\\\s]+\", batchflag=\"1\"}))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Cluster Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg(rocm_utilization_percentage)",
       "legendFormat": "GPU"
      },
      { "expr": "avg(rocm_vram_used_percentage)", "legendFormat": "GPU Memory Capacity" },
      { "expr": "avg(rocm_vram_busy_percentage)", "legendFormat": "GPU Memory Controller Activity" }
     ]
    },
    {
     "title": "GPU Utilization per Node",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1365 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%) in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1374 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage) * on (instance) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%) in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1374 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 742 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_celsius) * on (instance) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Average GPU Temperature in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 742 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_temperature_celsius) * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 751 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_temperature_memory_celsius) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(rocm_average_socket_power_watts) ",
       "legendFormat": "Power"
      }
     ]
    },
    {
     "title": "GPU Power per GPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 716 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_socket_power_watts) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Power in Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 725 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_average_socket_power_watts)  * on (instance) (rmsjob_info{jobid=~\"^[^\\\\s]+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Power in Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 725 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_average_socket_power_watts)  * on (instance) (rmsjob_info{jobid=\"\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Clock Frequency per GPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_sclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clock Frequency per GPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 699 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_mclk_clock_mhz) ",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Throttling Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Throttling Events per 1m",
     "type": "timeseries",
     "description": "Aggregating all throttling events in a node.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_throttle_events[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "# of Throttling Events per Node",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 683 },
     "targets": [
      {
       "expr": "sum by (instance) (rocm_throttle_events)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Reliability, Availability, and Serviceability (RAS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes with Non-zero Rate of Correctable Errors (errors/min)",
     "type": "timeseries",
     "description": "Aggregating all RAS events in each node. Only showing blocks/nodes with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_ras_umc_correctable_count[1m])) > 0",
       "legendFormat": "UMC: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_sdma_correctable_count[1m])) > 0",
       "legendFormat": "SDMA: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_gfx_correctable_count[1m])) > 0",
       "legendFormat": "GFX: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_mmhub_correctable_count[1m])) > 0",
       "legendFormat": "MMHUB: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_pcie_bif_correctable_count[1m])) > 0",
       "legendFormat": "PCIE BIF: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_hdp_correctable_count[1m])) > 0",
       "legendFormat": "HDP: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_xgmi_wafl_correctable_count[1m])) > 0",
       "legendFormat": "XGMI WAFL: {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes with Non-zero Rate of Uncorrectable Errors (errors/min)",
     "type": "timeseries",
     "description": "Aggregating all RAS events in each node. Only showing blocks/nodes with errors.  A panel with \"No data\" indicates no errors have been reported during the selected time window.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum by (instance) (delta(rocm_ras_umc_uncorrectable_count[1m])) > 0",
       "legendFormat": "UMC: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_sdma_uncorrectable_count[1m])) > 0",
       "legendFormat": "SDMA: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_gfx_uncorrectable_count[1m])) > 0",
       "legendFormat": "GFX: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_mmhub_uncorrectable_count[1m])) > 0",
       "legendFormat": "MMHUB: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_pcie_bif_uncorrectable_count[1m])) > 0",
       "legendFormat": "PCIE BIF: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_hdp_uncorrectable_count[1m])) > 0",
       "legendFormat": "HDP: {{instance}}"
      },
      {
       "expr": "sum by (instance) (delta(rocm_ras_xgmi_wafl_uncorrectable_count[1m])) > 0",
       "legendFormat": "XGMI WAFL: {{instance}}"
      }
     ]
    },
    {
     "title": "History of Correctable Errors per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 475 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_correctable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "History of Uncorrectable Errors per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 475 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_uncorrectable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes with Correctable Errors",
     "type": "table",
     "description": "A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 483 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_correctable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes with Uncorrectable Errors",
     "type": "table",
     "description": "A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 483 },
     "targets": [
      {
       "expr": "sum by (instance) ({__name__=~\"rocm_ras_.+_uncorrectable_count\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU - Video",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Cluster GPU Decoder Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg(rocm_average_decoder_utilization_percentage)",
       "legendFormat": "Decoder"
      }
     ]
    },
    {
     "title": "GPU Decoder Utilization (%) per Node",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 450 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_average_decoder_utilization_percentage)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Decoder Utilization (%) per GPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 459 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_average_decoder_utilization_percentage)",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 1m Load Average per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      { "expr": "omnistat_host_cpu_load1", "legendFormat": "Node: {{instance}}" }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 434 },
     "targets": [
      {
       "expr": "(omnistat_host_cpu_load1 * on (instance) group_left(jobid,user) (rmsjob_info{jobid=~\"^[^\\\\s]+\"}))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU 1m Load Average per Node - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 434 },
     "targets": [
      {
       "expr": "(omnistat_host_cpu_load1 * on (instance) group_left(jobid,user) (rmsjob_info{jobid=\"\"}))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(omnistat_host_mem_available_bytes) / sum(omnistat_host_mem_total_bytes)) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Memory (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 259 },
     "targets": [
      {
       "expr": "100 - (sum by (instance) (omnistat_host_mem_available_bytes) / sum by (instance) (omnistat_host_mem_total_bytes)) * 100",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO - Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Local Disk IO Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(omnistat_host_io_read_local_total_bytes[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(omnistat_host_io_write_local_total_bytes[$__rate_interval]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Local Disk IO Bandwidth per Node - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_host_io_read_local_total_bytes[$__rate_interval]))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Local Disk IO Bandwidth per Node - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_host_io_write_local_total_bytes[$__rate_interval]))",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Ethernet Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Ethernet Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(omnistat_network_rx_bytes{device_class=\"net\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(rate(omnistat_network_tx_bytes{device_class=\"net\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_rx_bytes{device_class=\"net\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_tx_bytes{device_class=\"net\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - High Performance Interconnect Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate High Performance Interconnect Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(sum by (instance) (rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval])))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(sum by (instance) (rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval])))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "High Performance Interconnect Bandwidth - Received - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval])) * on (instance) group_left(jobid,user) rmsjob_info{jobid=~\"^[^\\\\s]+\"}",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "High Performance Interconnect Bandwidth - Received - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_rx_bytes{device_class!=\"net\"}[$__rate_interval])) * on (instance) group_left(jobid,user) rmsjob_info{jobid=\"\"}",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "High Performance Interconnect Bandwidth - Transmitted - Allocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval])) * on (instance) group_left(jobid,user) rmsjob_info{jobid=~\"^[^\\\\s]+\"}",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "High Performance Interconnect Bandwidth - Transmitted - Unallocated Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(omnistat_network_tx_bytes{device_class!=\"net\"}[$__rate_interval])) * on (instance) group_left(jobid,user) rmsjob_info{jobid=\"\"}",
       "legendFormat": "Node: {{instance}}"
      }
     ]
    },
    {
     "title": "Aggregate High Performance Interconnect Errors",
     "type": "timeseries",
     "description": "Packet-level error counters from RoCE NICs, summed across the fleet as event rates. Sustained non-zero values indicate loss that may sharply degrade RDMA throughput.\n\n - **Out of Sequence (Rx)**: packets arrived with a gap in the sequence number.\n - **Retransmitted (Tx)**: packets this node re-sent after a NAK or timeout.\n - **Discarded (Rx/Tx)**: RoCE packets dropped by the NIC itself rather than lost in the fabric, usually from buffer exhaustion or malformed traffic.\n\nAvailability is vendor-specific. An absent series is unsupported, not zero: Ethernet, InfiniBand, and Slingshot report none of these.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(omnistat_network_rx_out_of_sequence_packets{}[$__rate_interval]))",
       "legendFormat": "Out of sequence (Rx)"
      },
      {
       "expr": "sum(rate(omnistat_network_tx_retransmitted_packets{}[$__rate_interval]))",
       "legendFormat": "Retransmitted (Tx)"
      },
      {
       "expr": "sum(rate(omnistat_network_rx_discarded_packets{}[$__rate_interval]))",
       "legendFormat": "Discarded (Rx)"
      },
      {
       "expr": "sum(rate(omnistat_network_tx_discarded_packets{}[$__rate_interval]))",
       "legendFormat": "Discarded (Tx)"
      }
     ]
    }
   ]
  }
 ]
}